package com.github.enerccio.marginalia.domain.collections;

/**
 * ISO 639-1 languages a book can be written in. English is listed first, the rest follows code order.
 */
public enum Language {
    ENGLISH("en", "English"),
    AFAR("aa", "Afar"),
    ABKHAZIAN("ab", "Abkhazian"),
    AVESTAN("ae", "Avestan"),
    AFRIKAANS("af", "Afrikaans"),
    AKAN("ak", "Akan"),
    AMHARIC("am", "Amharic"),
    ARAGONESE("an", "Aragonese"),
    ARABIC("ar", "Arabic"),
    ASSAMESE("as", "Assamese"),
    AVARIC("av", "Avaric"),
    AYMARA("ay", "Aymara"),
    AZERBAIJANI("az", "Azerbaijani"),
    BASHKIR("ba", "Bashkir"),
    BELARUSIAN("be", "Belarusian"),
    BULGARIAN("bg", "Bulgarian"),
    BISLAMA("bi", "Bislama"),
    BAMBARA("bm", "Bambara"),
    BENGALI("bn", "Bengali"),
    TIBETAN("bo", "Tibetan"),
    BRETON("br", "Breton"),
    BOSNIAN("bs", "Bosnian"),
    CATALAN("ca", "Catalan"),
    CHECHEN("ce", "Chechen"),
    CHAMORRO("ch", "Chamorro"),
    CORSICAN("co", "Corsican"),
    CREE("cr", "Cree"),
    CZECH("cs", "Czech"),
    CHURCH_SLAVIC("cu", "Church Slavic"),
    CHUVASH("cv", "Chuvash"),
    WELSH("cy", "Welsh"),
    DANISH("da", "Danish"),
    GERMAN("de", "German"),
    DIVEHI("dv", "Divehi"),
    DZONGKHA("dz", "Dzongkha"),
    EWE("ee", "Ewe"),
    GREEK("el", "Greek"),
    ESPERANTO("eo", "Esperanto"),
    SPANISH("es", "Spanish"),
    ESTONIAN("et", "Estonian"),
    BASQUE("eu", "Basque"),
    PERSIAN("fa", "Persian"),
    FULAH("ff", "Fulah"),
    FINNISH("fi", "Finnish"),
    FIJIAN("fj", "Fijian"),
    FAROESE("fo", "Faroese"),
    FRENCH("fr", "French"),
    WESTERN_FRISIAN("fy", "Western Frisian"),
    IRISH("ga", "Irish"),
    GAELIC("gd", "Gaelic"),
    GALICIAN("gl", "Galician"),
    GUARANI("gn", "Guarani"),
    GUJARATI("gu", "Gujarati"),
    MANX("gv", "Manx"),
    HAUSA("ha", "Hausa"),
    HEBREW("he", "Hebrew"),
    HINDI("hi", "Hindi"),
    HIRI_MOTU("ho", "Hiri Motu"),
    CROATIAN("hr", "Croatian"),
    HAITIAN("ht", "Haitian"),
    HUNGARIAN("hu", "Hungarian"),
    ARMENIAN("hy", "Armenian"),
    HERERO("hz", "Herero"),
    INTERLINGUA("ia", "Interlingua"),
    INDONESIAN("id", "Indonesian"),
    INTERLINGUE("ie", "Interlingue"),
    IGBO("ig", "Igbo"),
    SICHUAN_YI("ii", "Sichuan Yi"),
    INUPIAQ("ik", "Inupiaq"),
    IDO("io", "Ido"),
    ICELANDIC("is", "Icelandic"),
    ITALIAN("it", "Italian"),
    INUKTITUT("iu", "Inuktitut"),
    JAPANESE("ja", "Japanese"),
    JAVANESE("jv", "Javanese"),
    GEORGIAN("ka", "Georgian"),
    KONGO("kg", "Kongo"),
    KIKUYU("ki", "Kikuyu"),
    KUANYAMA("kj", "Kuanyama"),
    KAZAKH("kk", "Kazakh"),
    KALAALLISUT("kl", "Kalaallisut"),
    CENTRAL_KHMER("km", "Central Khmer"),
    KANNADA("kn", "Kannada"),
    KOREAN("ko", "Korean"),
    KANURI("kr", "Kanuri"),
    KASHMIRI("ks", "Kashmiri"),
    KURDISH("ku", "Kurdish"),
    KOMI("kv", "Komi"),
    CORNISH("kw", "Cornish"),
    KIRGHIZ("ky", "Kirghiz"),
    LATIN("la", "Latin"),
    LUXEMBOURGISH("lb", "Luxembourgish"),
    GANDA("lg", "Ganda"),
    LIMBURGAN("li", "Limburgan"),
    LINGALA("ln", "Lingala"),
    LAO("lo", "Lao"),
    LITHUANIAN("lt", "Lithuanian"),
    LUBA_KATANGA("lu", "Luba-Katanga"),
    LATVIAN("lv", "Latvian"),
    MALAGASY("mg", "Malagasy"),
    MARSHALLESE("mh", "Marshallese"),
    MAORI("mi", "Maori"),
    MACEDONIAN("mk", "Macedonian"),
    MALAYALAM("ml", "Malayalam"),
    MONGOLIAN("mn", "Mongolian"),
    MARATHI("mr", "Marathi"),
    MALAY("ms", "Malay"),
    MALTESE("mt", "Maltese"),
    BURMESE("my", "Burmese"),
    NAURU("na", "Nauru"),
    BOKMAL_NORWEGIAN("nb", "Bokmål, Norwegian"),
    NDEBELE_NORTH("nd", "Ndebele, North"),
    NEPALI("ne", "Nepali"),
    NDONGA("ng", "Ndonga"),
    DUTCH("nl", "Dutch"),
    NORWEGIAN_NYNORSK("nn", "Norwegian Nynorsk"),
    NORWEGIAN("no", "Norwegian"),
    NDEBELE_SOUTH("nr", "Ndebele, South"),
    NAVAJO("nv", "Navajo"),
    CHICHEWA("ny", "Chichewa"),
    OCCITAN("oc", "Occitan"),
    OJIBWA("oj", "Ojibwa"),
    OROMO("om", "Oromo"),
    ORIYA("or", "Oriya"),
    OSSETIAN("os", "Ossetian"),
    PANJABI("pa", "Panjabi"),
    PALI("pi", "Pali"),
    POLISH("pl", "Polish"),
    PUSHTO("ps", "Pushto"),
    PORTUGUESE("pt", "Portuguese"),
    QUECHUA("qu", "Quechua"),
    ROMANSH("rm", "Romansh"),
    RUNDI("rn", "Rundi"),
    ROMANIAN("ro", "Romanian"),
    RUSSIAN("ru", "Russian"),
    KINYARWANDA("rw", "Kinyarwanda"),
    SANSKRIT("sa", "Sanskrit"),
    SARDINIAN("sc", "Sardinian"),
    SINDHI("sd", "Sindhi"),
    NORTHERN_SAMI("se", "Northern Sami"),
    SANGO("sg", "Sango"),
    SINHALA("si", "Sinhala"),
    SLOVAK("sk", "Slovak"),
    SLOVENIAN("sl", "Slovenian"),
    SAMOAN("sm", "Samoan"),
    SHONA("sn", "Shona"),
    SOMALI("so", "Somali"),
    ALBANIAN("sq", "Albanian"),
    SERBIAN("sr", "Serbian"),
    SWATI("ss", "Swati"),
    SOTHO_SOUTHERN("st", "Sotho, Southern"),
    SUNDANESE("su", "Sundanese"),
    SWEDISH("sv", "Swedish"),
    SWAHILI("sw", "Swahili"),
    TAMIL("ta", "Tamil"),
    TELUGU("te", "Telugu"),
    TAJIK("tg", "Tajik"),
    THAI("th", "Thai"),
    TIGRINYA("ti", "Tigrinya"),
    TURKMEN("tk", "Turkmen"),
    TAGALOG("tl", "Tagalog"),
    TSWANA("tn", "Tswana"),
    TONGA("to", "Tonga"),
    TURKISH("tr", "Turkish"),
    TSONGA("ts", "Tsonga"),
    TATAR("tt", "Tatar"),
    TWI("tw", "Twi"),
    TAHITIAN("ty", "Tahitian"),
    UIGHUR("ug", "Uighur"),
    UKRAINIAN("uk", "Ukrainian"),
    URDU("ur", "Urdu"),
    UZBEK("uz", "Uzbek"),
    VENDA("ve", "Venda"),
    VIETNAMESE("vi", "Vietnamese"),
    VOLAPUK("vo", "Volapük"),
    WALLOON("wa", "Walloon"),
    WOLOF("wo", "Wolof"),
    XHOSA("xh", "Xhosa"),
    YIDDISH("yi", "Yiddish"),
    YORUBA("yo", "Yoruba"),
    ZHUANG("za", "Zhuang"),
    CHINESE("zh", "Chinese"),
    ZULU("zu", "Zulu");

    private final String code;
    private final String displayName;

    Language(String code, String displayName) {
        this.code = code;
        this.displayName = displayName;
    }

    /** ISO 639-1 code, usable as an HTML {@code lang} attribute. */
    public String getCode() {
        return code;
    }

    public String getDisplayName() {
        return displayName;
    }
}
