package com.github.enerccio.marginalia.loc;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Locale;

public class LocalizationEN extends LocalizationBase {

    @Override
    protected void loadMessages() {
        // --- LABEL ---
        setValue(L.LABEL_YES, "Yes");
        setValue(L.LABEL_NO, "No");
        setValue(L.LABEL_EXIT, "Exit");
        setValue(L.LABEL_USERNAME, "Username");
        setValue(L.LABEL_LOGIN, "Login");
        setValue(L.LABEL_LOGOUT, "Logout");
        setValue(L.LABEL_EXIT_APPLICATION, "Close application");
        setValue(L.LABEL_USER_FULLNAME, "Full Name");
        setValue(L.LABEL_CURRENT_PASSWORD, "Current Password");
        setValue(L.LABEL_EMAIL, "Email");
        setValue(L.LABEL_PASSWORD, "Password");
        setValue(L.LABEL_PASSWORD_AGAIN, "Repeat password");
        setValue(L.LABEL_FORGOT_PASSWORD, "Forgotten password?");
        setValue(L.LABEL_SAVE_LOGIN, "Save login");
        setValue(L.LABEL_AUTHENTICATION_FAILED, "Failed to authenticate");
        setValue(L.LABEL_APPLICATION_ERROR, "Application Error");
        setValue(L.LABEL_SAVE, "Save");
        setValue(L.LABEL_OK, "OK");
        setValue(L.LABEL_CANCEL, "Cancel");
        setValue(L.LABEL_MODELS, "Inference Providers");
        setValue(L.LABEL_ADD_MODEL, "Add Inference Provider");
        setValue(L.LABEL_TYPE, "Type");
        setValue(L.LABEL_NAME, "Name");
        setValue(L.LABEL_EDIT, "Edit");
        setValue(L.LABEL_ADMIN, "Admin");
        setValue(L.LABEL_EDIT_AI, "Edit Inference Provider");
        setValue(L.LABEL_NEW_AI, "New Inference Provider");
        setValue(L.LABEL_URL, "OpenAI URL (ends with /v1)");
        setValue(L.LABEL_API_KEY, "Api Key");
        setValue(L.LABEL_RESET, "Reset Api Key");
        setValue(L.LABEL_MODEL, "Model");
        setValue(L.LABEL_REFRESH, "Refresh");
        setValue(L.LABEL_MAX_CONTEXT, "Max Context Size");
        setValue(L.LABEL_MAX_RESPONSE, "Max Response Tokens");
        setValue(L.LABEL_ADDITIONAL_PARAMETERS, "Additional Parameters");
        setValue(L.LABEL_ADMINISTRATOR, "Administrator");
        setValue(L.LABEL_GENERAL_SETTINGS, "General Settings");
        setValue(L.LABEL_TYPE_SETTINGS, "Per Type Settings");
        setValue(L.LABEL_JAILBREAK, "Jailbreak Prompt");
        setValue(L.LABEL_NEEDS_JAILBREAK, "Needs Jailbreak");
        setValue(L.LABEL_ENABLED_REASONING, "Enable Reasoning");
        setValue(L.LABEL_REASONING_EFFORT, "Reasoning Effort");
        setValue(L.LABEL_PROTOCOLS, "Protocols");
        setValue(L.LABEL_ADD_PROTOCOL, "Add Protocol");
        setValue(L.LABEL_EDIT_PROTOCOL, "Edit Protocol");
        setValue(L.LABEL_NEW_PROTOCOL, "New Protocol");
        setValue(L.LABEL_MAX_TOKENS, "Max Context Tokens");
        setValue(L.LABEL_REPLY_TOKENS, "Max Reply Tokens");
        setValue(L.LABEL_ENABLE_TEMPERATURE, "Enable Temperature");
        setValue(L.LABEL_TEMPERATURE, "Temperature");
        setValue(L.LABEL_ENABLE_TOP_P, "Enable Top P");
        setValue(L.LABEL_TOP_P, "Top P");
        setValue(L.LABEL_ENABLE_FREQUENCY_PENALTY, "Enable Frequency Penalty");
        setValue(L.LABEL_FREQUENCY_PENALTY, "Frequency Penalty");
        setValue(L.LABEL_ENABLE_PRESENCE_PENALTY, "Enable Presence Penalty");
        setValue(L.LABEL_PRESENCE_PENALTY, "Presence Penalty");
        setValue(L.LABEL_SETTINGS, "Settings");
        setValue(L.LABEL_DEFAULT_MODEL, "Default Model");
        setValue(L.LABEL_DEFAULT_PROTOCOL, "Default Protocol");
        setValue(L.LABEL_TEMPLATES, "Templates");
        setValue(L.LABEL_MASTER_TEMPLATE, "Master Template");
        setValue(L.LABEL_POV, "Point of View (POV)");
        setValue(L.LABEL_TENSE, "Tense");
        setValue(L.LABEL_STYLE, "Style");
        setValue(L.LABEL_SUMMARY_PROMPT, "Default Summary Prompt");
        setValue(L.LABEL_USER_PROMPT, "Default User Prompt");
        setValue(L.LABEL_AVAILABLE_VARIABLES, "Available Template Variables");
        setValue(L.LABEL_FILL_DEFAULT, "Insert Default Template");
        setValue(L.LABEL_LOREBOOKS, "Lorebooks");
        setValue(L.LABEL_ADD_LOREBOOK, "Add Lorebook");
        setValue(L.LABEL_EDIT_LOREBOOK, "Edit Lorebook");
        setValue(L.LABEL_NEW_LOREBOOK, "New Lorebook");
        setValue(L.LABEL_NEW_LOREBOOK_ENTRY, "New Entry");
        setValue(L.LABEL_DELETE_LOREBOOK, "Delete Lorebook");
        setValue(L.LABEL_SUB_LOREBOOKS, "Sub Lorebooks");
        setValue(L.LABEL_ADD_ENTRY, "Add Entry");
        setValue(L.LABEL_DELETE_ENTRY, "Delete Entry");
        setValue(L.LABEL_ENTRY_NAME, "Entry Name");
        setValue(L.LABEL_ORDER, "Order");
        setValue(L.LABEL_ENABLED, "Enabled");
        setValue(L.LABEL_CONTENT, "Content");
        setValue(L.LABEL_NOTE, "Note");
        setValue(L.LABEL_TAGS, "Tags");
        setValue(L.LABEL_LOREBOOK, "Lorebook");
        setValue(L.LABEL_DELETE, "Delete");
        setValue(L.LABEL_BOOKS, "Books");
        setValue(L.LABEL_BOOK, "Book");
        setValue(L.LABEL_ADD_BOOK, "Add Book");
        setValue(L.LABEL_EDIT_BOOK, "Edit Book");
        setValue(L.LABEL_NEW_BOOK, "New Book");
        setValue(L.LABEL_NEGATIVE_TAGS, "Negative Tags (Exclusion)");
        setValue(L.LABEL_INFO_PART, "About");
        setValue(L.LABEL_PROMPT_PART, "Prompts");
        setValue(L.LABEL_STORY_PART, "Story");
        setValue(L.LABEL_DESCRIPTION, "Description");
        setValue(L.LABEL_TOTAL_WORD_COUNT, "Total Word Count");
        setValue(L.LABEL_TOTAL_TOKEN_COUNT, "Total Token Count");
        setValue(L.LABEL_BRANCH_WORD_COUNT, "Active Branch Word Count");
        setValue(L.LABEL_BRANCH_TOKEN_COUNT, "Active Branch Token Count");
        setValue(L.LABEL_STORY_CONTROLS, "Story Controls");
        setValue(L.LABEL_GENERATE_NEXT, "Generate Next");
        setValue(L.LABEL_BRANCH_STORY, "Branch Story");
        setValue(L.LABEL_NODE_METADATA, "Node Metadata");
        setValue(L.LABEL_VIEW_REASONING, "View Reasoning");
        setValue(L.LABEL_TOKENS, "Tokens");
        setValue(L.LABEL_WORDS, "Words");
        setValue(L.LABEL_SCENE_SETTING, "Scene Setting");
        setValue(L.LABEL_POV_CHARACTER, "POV Character");
        setValue(L.LABEL_PRESENT_CHARACTERS, "Present Characters");
        setValue(L.LABEL_INSTRUCTIONS, "Instructions");
        setValue(L.LABEL_NEW_TURN_INSTRUCTIONS, "New Turn Instructions");
        setValue(L.LABEL_GENERATE, "Generate");
        setValue(L.LABEL_TURN_DETAILS, "Turn Details");
        setValue(L.LABEL_IMPORT_FROM_SILLYTAVERN, "Import from SillyTavern");
        setValue(L.LABEL_CHANGE_STYLES, "Change Styles For Text");
        setValue(L.LABEL_REGENERATE, "Regenerate");
        setValue(L.LABEL_SWIPE, "Swipe");
        setValue(L.LABEL_SHOW_PROMPT, "Show Prompt");
        setValue(L.LABEL_CHAPTERS, "Outline");
        setValue(L.LABEL_CHAPTER_OUTLINE_HEADER, "Story Branch (%s)");
        setValue(L.LABEL_CHAPTER_OUTLINE_NODE, "#%s (DB ID: %s)");
        setValue(L.LABEL_GENERATE_SUMMARY, "Generate summary");
        setValue(L.LABEL_SHOW_SUMMARY, "View summary");
        setValue(L.LABEL_DELETE_SUMMARY, "Delete summary");
        setValue(L.LABEL_MESSAGE_IDS, "Order #%s | DB ID: %s");
        setValue(L.LABEL_GENERATING_SUMMARY, "Generating Summary");
        setValue(L.LABEL_SUMMARY, "Summary");
        setValue(L.LABEL_STOP, "Stop");
        setValue(L.LABEL_SUMMARY_STOPPED, "Summary Terminated");
        setValue(L.LABEL_SUMMARY_ERROR, "Summary Error");
        setValue(L.LABEL_EXTENSIONS, "Extensions");
        setValue(L.LABEL_UPLOAD_EXTENSION, "Load Extension (.jar)");
        setValue(L.LABEL_UNLOAD_EXTENSION, "Unload");
        setValue(L.LABEL_BUNDLE_ID, "ID");
        setValue(L.LABEL_BUNDLE_NAME, "Extension Name");
        setValue(L.LABEL_BUNDLE_VERSION, "Version");
        setValue(L.LABEL_BUNDLE_STATE, "State");
        setValue(L.LABEL_ACTIONS, "Actions");
        setValue(L.LABEL_EXTENSION_SETTINGS, "Extension Settings");
        setValue(L.LABEL_BRANCH_TREE, "Branch view");
        setValue(L.LABEL_BACKUPS, "Backups");
        setValue(L.LABEL_TAKE_BACKUP, "Take Backup");
        setValue(L.LABEL_RESTORE_BACKUP, "Restore");
        setValue(L.LABEL_CLONE_BACKUP, "Clone Backup");
        setValue(L.LABEL_IMPORT_BACKUP, "Import Backup");
        setValue(L.LABEL_EXPORT_BACKUP, "Export");
        setValue(L.LABEL_IMPORT_BACKUP_AS_NEW, "Import Backup as New Book");
        setValue(L.LABEL_BACKUP_DATE, "Date");
        setValue(L.LABEL_MESSAGES_COUNT, "Messages");
        setValue(L.LABEL_FULL_RESTORE, "Full Restore");
        setValue(L.LABEL_MESSAGES_ONLY_RESTORE, "Messages Only Restore");
        setValue(L.LABEL_NEW_MANUSCRIPT_NAME, "New Book Name");
        setValue(L.LABEL_RESTORE_OPTION_TITLE, "Select Restore Option");
        setValue(L.LABEL_RESTORE_OPTION_MSG, "Choose how you want to restore this backup:");
        setValue(L.LABEL_BACKUP_STRATEGY, "Backup Strategy");
        setValue(L.LABEL_BACKUP_STRATEGY_VALUE_MESSAGES, "Number of messages");
        setValue(L.LABEL_BACKUP_STRATEGY_VALUE_MINUTES, "Number of minutes");
        setValue(L.LABEL_PER_MANUSCRIPT_BACKUP, "Per manuscript override");
        setValue(L.LABEL_DELETE_BACKUP, "Delete Backup");
        setValue(L.LABEL_CREATED, "Created");
        setValue(L.LABEL_LAST_MODIFIED, "Last Modified");
        setValue(L.LABEL_FILTERING_MODE, "Filtering Mode");
        setValue(L.LABEL_FILTERING, "Filtering Text/Pattern");
        setValue(L.LABEL_INSERTION_MODE, "Insertion Mode");
        setValue(L.LABEL_VIEWER_TITLE, "Marginalia - Viewer");
        setValue(L.LABEL_VIEWER_DESC, "Manuscript Viewer");
        setValue(L.LABEL_AVAILABLE_MACROS, "Available Macros");
        setValue(L.LABEL_USERS, "Users");
        setValue(L.LABEL_ADD_USER, "Add User");
        setValue(L.LABEL_EDIT_USER, "Edit User");
        setValue(L.LABEL_NEW_USER, "New User");
        setValue(L.LABEL_CHANGE_PASSWORD, "Change Password");
        setValue(L.LABEL_EXPORT_LOREBOOK, "Export Lorebook");
        setValue(L.LABEL_IMPORT_LOREBOOK, "Import Marginalia Lorebook");
        setValue(L.LABEL_DATABASE_BACKUPS, "Database Backups");
        setValue(L.LABEL_CREATE_BACKUP, "Create Backup");
        setValue(L.LABEL_UPLOAD_BACKUP, "Upload Backup");
        setValue(L.LABEL_DOWNLOAD, "Download");
        setValue(L.LABEL_SIZE, "Size");
        setValue(L.LABEL_DATABASE_SIZE, "Current database size: %s");
        setValue(L.LABEL_RESTORE_ON_RESTART, "Restore on restart");
        setValue(L.LABEL_CANCEL_RESTORE, "Cancel Restore");
        setValue(L.LABEL_SCHEDULED_BACKUPS, "Scheduled Backups");
        setValue(L.LABEL_BACKUP_SCHEDULE_ENABLED, "Create backups automatically");
        setValue(L.LABEL_BACKUP_SCHEDULE, "Schedule (cron)");
        setValue(L.LABEL_BACKUP_KEEP, "Keep scheduled backups");
        setValue(L.LABEL_SAVE_SCHEDULE, "Save Schedule");
        setValue(L.LABEL_NEVER, "never");
        setValue(L.LABEL_BACKUP_MANUAL, "Manual");
        setValue(L.LABEL_BACKUP_SCHEDULED, "Scheduled");
        setValue(L.LABEL_CLEANUP, "Cleanup");
        setValue(L.LABEL_ANALYZE, "Analyze");
        setValue(L.LABEL_RUN_CLEANUP, "Run Cleanup");
        setValue(L.LABEL_ENTITY, "Entity");
        setValue(L.LABEL_SOFT_DELETED, "Deleted");
        setValue(L.LABEL_PURGEABLE, "To purge");
        setValue(L.LABEL_BLOCKED, "Blocked");
        setValue(L.LABEL_BLOCKED_ENTITIES, "Deleted objects still in use");
        setValue(L.LABEL_REFERENCED_BY, "Referenced by");
        setValue(L.LABEL_REFERENCE_MODEL, "Reference Model");
        setValue(L.LABEL_REFERRER, "Referrer");
        setValue(L.LABEL_FIELD, "Field");
        setValue(L.LABEL_TARGET, "Target");
        setValue(L.LABEL_POLICY, "Policy");
        setValue(L.LABEL_LOREBOOKS_SAME_NAME, "Lorebooks with the same name found");
        setValue(L.LABEL_IMPORT_LOREBOOKS, "Import lorebooks");
        setValue(L.LABEL_STATUS, "Status");
        setValue(L.LABEL_ENTRIES, "Entries");
        setValue(L.LABEL_ACTION, "Action");
        setValue(L.LABEL_USED_BY_BOOK, "Used by book");
        setValue(L.LABEL_CONTINUE, "Continue");
        setValue(L.LABEL_IMPORT, "Import");
        setValue(L.LABEL_DONT_IMPORT, "Don't import");
        setValue(L.LABEL_LAST_OPENED, "Last Opened");
        setValue(L.LABEL_PUBLISHED, "Published");
        setValue(L.LABEL_CLEAR_PASSWORD, "Clear password");
        setValue(L.LABEL_DISCARD_CHANGES, "Discard Changes");
        setValue(L.LABEL_UNLOCK_ACCOUNT, "Unlock account (too many failed logins)");
        setValue(L.LABEL_LANGUAGE, "Language");
        setValue(L.LABEL_FIT_TEXT_AREA_TO_CONTENT, "Grow to fit the whole text");
        setValue(L.LABEL_FIXED_TEXT_AREA_HEIGHT, "Fixed height, scroll the text");
        setValue(L.LABEL_EXPORT_STORY, "Export story");
        setValue(L.LABEL_EXPORT_FORMAT, "Format");
        setValue(L.LABEL_FILE_NAME, "File name");
        setValue(L.LABEL_BOOK_TITLE, "Book title");
        setValue(L.LABEL_AUTHOR, "Author");
        setValue(L.LABEL_FROM_MESSAGE, "From message");
        setValue(L.LABEL_TO_MESSAGE, "To message (empty for the end)");
        setValue(L.LABEL_INCLUDE_TITLE_PAGE, "Include title page");
        setValue(L.LABEL_CLOSE, "Close");
        setValue(L.LABEL_META_SUMMARY_PROMPT, "Default Meta Summary Prompt");
        setValue(L.LABEL_UNWIND, "Unwind");
        setValue(L.LABEL_SUMMARIES, "Summaries");
        setValue(L.LABEL_MESSAGE_ID, "Message ID");
        setValue(L.LABEL_SELECT, "Select");
        setValue(L.LABEL_CREATE_META_SUMMARY, "Create meta summary");
        setValue(L.LABEL_GENERATING_META_SUMMARY, "Generating Meta Summary");
        setValue(L.LABEL_META_SUMMARY, "Meta summary");
        setValue(L.LABEL_REPLACED_SUMMARY, "Replaced");
        setValue(L.LABEL_IMAGES, "Images");
        setValue(L.LABEL_ADD_IMAGE, "Add image");
        setValue(L.LABEL_IMAGE_CAPTION, "Caption");
        setValue(L.LABEL_REMOVE_IMAGE, "Remove image");
        setValue(L.LABEL_RESOURCES, "Resources");
        setValue(L.LABEL_LINKED_OBJECT, "Used by");
        setValue(L.LABEL_REPLACE_CONTENT, "Replace content");
        setValue(L.LABEL_DELETE_SELECTED, "Delete selected");
        setValue(L.LABEL_WITH_IMAGES, "With images");
        setValue(L.LABEL_WITHOUT_IMAGES, "Without images");
        setValue(L.LABEL_REQUEST_TIMEOUT, "Timeout (seconds)");
        setValue(L.LABEL_MAX_RETRIES, "Retries");
        setValue(L.LABEL_TEST_CONNECTION, "Test Connection");

        // --- ENUM ---
        setValue(L.ENUM_AI_TYPE_OPEN_AI_COMPATIBLE, "OpenAI Compatible");
        setValue(L.ENUM_PROTOCOL_TYPE_OPEN_CHAT_COMPLETION, "Chat Completion");
        setValue(L.ENUM_REASONING_NONE, "None");
        setValue(L.ENUM_REASONING_LOW, "Low");
        setValue(L.ENUM_REASONING_MEDIUM, "Medium");
        setValue(L.ENUM_REASONING_HIGH, "High");
        setValue(L.ENUM_BACKUP_STRATEGY_NONE, "No Backups");
        setValue(L.ENUM_BACKUP_STRATEGY_AFTER_N_MESSAGES, "After N Messages");
        setValue(L.ENUM_BACKUP_STRATEGY_AFTER_N_MINUTES, "After N Minutes");
        setValue(L.ENUM_FILTERING_MODE_TEXT, "Text");
        setValue(L.ENUM_FILTERING_MODE_REGEX, "Regex");
        setValue(L.ENUM_INSERTION_MODE_IN_LORE_BLOCK, "In Lore Block");
        setValue(L.ENUM_INSERTION_MODE_BEFORE_USER_PROMPT, "Before User Prompt");
        setValue(L.ENUM_CLEANUP_POLICY_STRONG, "Blocks purge");
        setValue(L.ENUM_CLEANUP_POLICY_OWNED_BY, "Purged with target");
        setValue(L.ENUM_CLEANUP_POLICY_OWNS, "Owns target");
        setValue(L.ENUM_CLEANUP_POLICY_WEAK, "Cleared on purge");
        setValue(L.ENUM_LOREBOOK_MATCH_EXISTING, "Already exists");
        setValue(L.ENUM_LOREBOOK_MATCH_SAME_NAME, "Same name exists");
        setValue(L.ENUM_LOREBOOK_MATCH_NOT_FOUND, "Not found");
        setValue(L.ENUM_LOREBOOK_DECISION_LINK, "Link to existing");
        setValue(L.ENUM_LOREBOOK_DECISION_CREATE, "Create new");
        setValue(L.ENUM_LOREBOOK_DECISION_SKIP, "Skip");

        // --- ERROR ---
        setValue(L.ERROR_INTERNAL_SERVER_ERROR, "Internal Server Error");
        setValue(L.ERROR_AI_NOT_SET, "Book is missing model.");
        setValue(L.ERROR_PROTOCOL_NOT_SET, "Book is missing protocol.");
        setValue(L.ERROR_CONTEXT_INSUFFICIENT, "Contextual limit not sufficient.");
        setValue(L.ERROR_EXTENSION_INSTALL_FAILED, "Failed to load extension: %s");
        setValue(L.ERROR_EXTENSION_UNINSTALL_FAILED, "Failed to unload extension: %s");
        setValue(L.ERROR_MANUSCRIPT_NULL, "Manuscript cannot be null.");
        setValue(L.ERROR_BACKUP_NULL, "Manuscript and backup cannot be null.");
        setValue(L.ERROR_BACKUP_DATA_EMPTY, "Backup data cannot be empty.");
        setValue(L.ERROR_BACKUP_INVALID_JSON, "Invalid backup payload: Unable to parse JSON.");
        setValue(L.ERROR_BACKUP_INVALID_ROOT_OBJECT, "Invalid backup payload: Root must be a JSON object.");
        setValue(L.ERROR_BACKUP_MISSING_CONTENT, "Invalid backup structure: Missing manuscript backup content.");
        setValue(L.ERROR_BACKUP_MISSING_METADATA, "Invalid backup metadata: Missing required fields.");
        setValue(L.ERROR_MANUSCRIPT_UUID_NULL, "Manuscript and its UUID cannot be null.");
        setValue(L.ERROR_SUMMARY_FAILED, "Failed to reach inference service for generating summary.");
        setValue(L.ERROR_NAME_CANT_BE_EMPTY, "Name can't be empty.");
        setValue(L.ERROR_EXPORT_RANGE_INVALID, "The last message can't be before the first message.");
        setValue(L.ERROR_INVALID_IMAGE, "The file is not a PNG, JPEG, GIF or WebP image, or it is larger than 10 MB.");
        setValue(L.ERROR_INFERENCE_DETAILS, "%s Provider says: %s");
        setValue(L.ERROR_INFERENCE_AUTHENTICATION, "The provider rejected the API key. Check the API key of the inference provider.");
        setValue(L.ERROR_INFERENCE_PERMISSION, "The API key is not allowed to use this model or endpoint.");
        setValue(L.ERROR_INFERENCE_MODEL_NOT_FOUND, "The provider does not know the configured model. Check the model of the inference provider.");
        setValue(L.ERROR_INFERENCE_NOT_FOUND, "Nothing was found at the configured URL. Check the URL of the inference provider (it usually ends with /v1).");
        setValue(L.ERROR_INFERENCE_CONTEXT_OVERFLOW, "The prompt does not fit into the context of the model. Lower Max Context Size or the response size, or use a model with a larger context.");
        setValue(L.ERROR_INFERENCE_RATE_LIMIT, "The provider is limiting requests (rate limit or quota). Wait a moment and try again.");
        setValue(L.ERROR_INFERENCE_SERVER, "The provider failed to process the request. Try again later.");
        setValue(L.ERROR_INFERENCE_TIMEOUT, "The provider did not answer in time. Try again or raise the timeout of the inference provider.");
        setValue(L.ERROR_INFERENCE_CONNECTION, "Cannot connect to the provider. Check the URL of the inference provider and your network.");
        setValue(L.ERROR_INFERENCE_BAD_REQUEST, "The provider rejected the request. Check the model and the additional parameters of the inference provider.");
        setValue(L.ERROR_INFERENCE_UNKNOWN, "The request to the provider failed.");

        // --- MSG ---
        setValue(L.MSG_VALIDATION_FAILED_CANT_SAVE, "Cannot save form.");
        setValue(L.MSG_VALIDATION_FAILED_CANT_SAVE_EXT, "Cannot save form. Invalid fields: ");
        setValue(L.MSG_AUTHENTICATION_FAILED_INFO, "Invalid credentials.");
        setValue(L.MSG_INVALID_JSON_OBJECT, "JSON Invalid.");
        setValue(L.MSG_FETCH_MODELS_FAILED, "Failed to download model list.");
        setValue(L.MSG_SETTINGS_SAVED, "Settings saved successfully.");
        setValue(L.MSG_CONFIRM_DELETE, "Are you sure you want to delete this item?");
        setValue(L.MSG_CYCLE_DETECTED, "Cannot select sub lorebook: cycle detected.");
        setValue(L.MSG_NO_ACTIVE_BRANCH, "No active story branch. Add a message to begin.");
        setValue(L.MSG_SELECT_MESSAGE_METADATA, "Select a message to view metadata.");
        setValue(L.MSG_INTERRUPTED, "Generation interrupted on the backend.");
        setValue(L.MSG_SUMMARY_FAILURE, "Invalidated summaries for messages with IDs: [%s]. Continue generation without those summaries?");
        setValue(L.MSG_EXTENSION_INSTALLED_SUCCESS, "Extension loaded successfully.");
        setValue(L.MSG_EXTENSION_UNINSTALLED_SUCCESS, "Extension unloaded successfully.");
        setValue(L.MSG_CONFIRM_UNLOAD_EXTENSION, "Extension \"%s\" will be unloaded and its JAR deleted from the extensions folder. Continue?");
        setValue(L.MSG_INVALID_TEMPLATE, "Invalid template: ");
        setValue(L.MSG_TEMPLATE_UNKNOWN_NAMES, "Unknown names (sent to the model as \"Error\"): ");
        setValue(L.MSG_LOGIN_ALREADY_EXISTS, "User with this login already exists.");
        setValue(L.MSG_PASSWORDS_DO_NOT_MATCH, "Passwords do not match.");
        setValue(L.MSG_CANNOT_DELETE_SELF, "You cannot delete your own account.");
        setValue(L.MSG_CANNOT_DELETE_LAST_ADMIN, "The last administrator cannot be deleted or demoted.");
        setValue(L.MSG_INVALID_LOREBOOK_FILE, "File is not a valid Marginalia lorebook export.");
        setValue(L.MSG_DATABASE_BACKUP_CREATED, "Database backup created.");
        setValue(L.MSG_CONFIRM_DATABASE_RESTORE, "Database will be replaced with backup \"%s\" on next application start. Current database will be kept in backup folder. Continue?");
        setValue(L.MSG_DATABASE_RESTORE_PENDING, "Database restore is scheduled. Restart the application to apply it.");
        setValue(L.MSG_INVALID_DATABASE_FILE, "The database can't be restored: %s.");
        setValue(L.MSG_BACKUP_SCHEDULE_NEXT, "Next backups: %s");
        setValue(L.MSG_BACKUP_SCHEDULE_INVALID, "Invalid schedule: %s");
        setValue(L.MSG_BACKUP_SCHEDULE_SAVED, "Backup schedule saved.");
        setValue(L.MSG_BACKUP_SCHEDULE_OFF, "Scheduled backups are off.");
        setValue(L.MSG_BACKUP_SCHEDULE_STATUS, "Last scheduled backup: %s. Next: %s.");
        setValue(L.MSG_ADMIN_ONLY, "Only administrators can do this.");
        setValue(L.MSG_CLEANUP_DESCRIPTION, "Cleanup permanently removes deleted objects that are no longer used anywhere, together with data that belongs only to them (messages, entries, tag relations...). Deleted objects that are still referenced are kept.");
        setValue(L.MSG_CONFIRM_CLEANUP, "%d objects will be permanently removed. Consider creating database backup first. Continue?");
        setValue(L.MSG_CLEANUP_DONE, "Cleanup removed %d objects.");
        setValue(L.MSG_NOTHING_TO_CLEANUP, "There is nothing to clean up.");
        setValue(L.MSG_LOREBOOKS_SAME_NAME, "Some lorebooks in the backup have the same name as your existing lorebooks. Choose whether to link to the existing lorebook or create a new one from the backup.");
        setValue(L.MSG_IMPORT_LOREBOOKS, "Some lorebooks in the backup were not found. Do you want to import them as well?");
        setValue(L.MSG_PUBLISHED_HELP, "Published books can be read by other users through the reader link.");
        setValue(L.MSG_MANUSCRIPT_NOT_FOUND, "Book not found.");
        setValue(L.MSG_AI_RESPONSE_EXCEEDS_CONTEXT, "Max Response Tokens must be lower than Max Context Size.");
        setValue(L.MSG_NO_PASSWORD_WARNING, "Warning! No password provided. If this is a server instance, please provide password for every user. Are you sure you want to save user with blank password?");
        setValue(L.MSG_CLEAR_PASSWORD_WARNING, "The password will be removed and the user's saved logins ended. The user then logs in with the user name only, anyone who knows it can log in until a new password is set. Continue?");
        setValue(L.MSG_UNSAVED_SETTINGS, "Unsaved changes - save or discard them to leave the tab.");
        setValue(L.MSG_EXPORT_COLLECTING, "Collecting messages...");
        setValue(L.MSG_EXPORTING, "Exporting the story...");
        setValue(L.MSG_EXPORT_READY, "The export is ready: %s");
        setValue(L.MSG_EXPORT_NOTHING, "There is nothing to export in the selected range.");
        setValue(L.MSG_CONFIRM_DELETE_META_SUMMARY, "This is a meta summary. Unwind it to restore the summary it replaced, or delete it completely?");
        setValue(L.MSG_ACTIVE_SUMMARIES_TOKENS, "Active summaries: %s tokens");
        setValue(L.MSG_META_SUMMARY_SELECTION, "Select at least two summaries to merge.");
        setValue(L.MSG_RESOURCE_NOT_LINKED, "nothing");
        setValue(L.MSG_RESOURCE_LINK_MISSING, "%s (gone)");
        setValue(L.MSG_RESOURCE_REPLACED, "The content was replaced.");
        setValue(L.MSG_CONFIRM_DELETE_RESOURCES, "Delete %s selected resources? Whatever uses them will lose them. The files stay in the data folder.");
        setValue(L.MSG_RESOURCES_EMPTY, "There are no resources yet. Pictures you add to a part of a book are listed here.");
        setValue(L.MSG_BACKUP_EXPORT_IMAGES, "This backup uses %s images. They are not stored in the backup, only their list. Pack them into the downloaded file? It becomes a .zip and can be much larger.");
        setValue(L.MSG_CLONE_BACKUP_IMAGES, "This backup uses %s images. Give the clone its own copies of them? Images you have deleted since are left out.");
        setValue(L.MSG_PACKING_BACKUP, "Packing the backup");
        setValue(L.MSG_BACKUP_READY, "The backup is ready: %s");
        setValue(L.MSG_BACKUP_IMAGES_MISSING, "%s images could not be packed, because they were deleted or their files are missing.");
        setValue(L.MSG_CONNECTION_OK, "Connection works: %s models available and the model answered.");
        setValue(L.MSG_CONNECTION_OK_NO_MODELS, "Connection works: the model answered (the provider does not list its models).");
        setValue(L.MSG_PROMPT_MAY_OVERFLOW, "The prompt has about %s tokens and %s are kept for the response, the context size is %s. The provider may reject the request or cut the prompt.");

        // --- HELP ---
        setValue(L.HELP_BACKUP_SCHEDULE, "minute hour day-of-month month day-of-week - e.g. \"0 3 * * *\" every day at 3:00, \"0 */6 * * *\" every 6 hours, \"30 2 * * 1\" Mondays at 2:30. @daily, @weekly and @monthly work too.");
        setValue(L.HELP_BACKUP_KEEP, "Older scheduled backups are deleted, 0 keeps all. Manual backups are never deleted.");
        setValue(L.HELP_AI_MAX_CONTEXT, "Total tokens the model accepts - prompt and response together.");
        setValue(L.HELP_AI_MAX_RESPONSE, "Longest response. This much of the context is kept free for the response.");
        setValue(L.HELP_PROTOCOL_MAX_TOKENS, "Optional. Empty uses Max Context Size of the inference provider.");
        setValue(L.HELP_PROTOCOL_REPLY_TOKENS, "Optional. Empty uses Max Response Tokens of the inference provider.");
        setValue(L.HELP_AI_REQUEST_TIMEOUT, "How long to wait for the provider to answer or to send more text. Reasoning models may need minutes before the first text.");
        setValue(L.HELP_AI_MAX_RETRIES, "Retries of a request that failed with a rate limit (429), a server error (5xx) or a connection error. The wait between them grows.");

        // --- DESC ---
        setValue(L.DESC_TEMPLATE_BACKGROUND_LORE, "Background lore and world context.");
        setValue(L.DESC_TEMPLATE_MANUSCRIPT, "The ongoing manuscript content for summary.");
        setValue(L.DESC_TEMPLATE_NARRATIVE_POV, "Point of view (POV) for the narrative.");
        setValue(L.DESC_TEMPLATE_NARRATIVE_TENSE, "Tense used for the narrative.");
        setValue(L.DESC_TEMPLATE_STYLE, "Style and tone guidelines.");
        setValue(L.DESC_TEMPLATE_POV_CHARACTER, "Point of view character for the scene.");
        setValue(L.DESC_TEMPLATE_SCENE_SETTING, "Current location and scene setting.");
        setValue(L.DESC_TEMPLATE_PRESENT_CHARACTERS, "Characters currently present in the scene.");
        setValue(L.DESC_TEMPLATE_INSTRUCTIONS, "Plot specifications and instructions for continuation.");
        setValue(L.DESC_TEMPLATE_SUMMARIES, "Summaries.");
        setValue(L.DESC_TEMPLATE_MANUSCRIPT_NAME, "Name of the book.");
        setValue(L.DESC_TEMPLATE_MANUSCRIPT_DESCRIPTION, "Description of the book.");
        setValue(L.DESC_MACRO_USER, "Protagonist of the scene (the POV character). SillyTavern's persona name.");
        setValue(L.DESC_MACRO_CHAR, "Character name - the POV character.");
        setValue(L.DESC_MACRO_GROUP, "Characters present in the scene (POV character if not set).");
        setValue(L.DESC_MACRO_NOT_CHAR, "Present characters except the POV character.");
        setValue(L.DESC_MACRO_DESCRIPTION, "Manuscript description.");
        setValue(L.DESC_MACRO_SCENARIO, "Current scene setting.");
        setValue(L.DESC_MACRO_INPUT, "Instructions written for the current continuation.");
        setValue(L.DESC_MACRO_LAST_MESSAGE, "Last story part of the current branch.");
        setValue(L.DESC_MACRO_LAST_MESSAGE_ID, "Index of the last story part of the current branch.");
        setValue(L.DESC_MACRO_LAST_USER_MESSAGE, "Instructions used for the last story part.");
        setValue(L.DESC_MACRO_SUMMARY, "Latest summary of the current branch.");
        setValue(L.DESC_MACRO_TIME, "Current time, optionally with UTC offset.");
        setValue(L.DESC_MACRO_DATE, "Current date.");
        setValue(L.DESC_MACRO_WEEKDAY, "Current day of the week.");
        setValue(L.DESC_MACRO_ISOTIME, "Current time in HH:mm format.");
        setValue(L.DESC_MACRO_ISODATE, "Current date in YYYY-MM-DD format.");
        setValue(L.DESC_MACRO_DATETIMEFORMAT, "Current date/time in custom (moment.js) format.");
        setValue(L.DESC_MACRO_IDLE_DURATION, "Time since the last story part was generated.");
        setValue(L.DESC_MACRO_TIME_DIFF, "Human readable difference between two times.");
        setValue(L.DESC_MACRO_GETVAR, "Value of a local variable. Local variables follow the story branch.");
        setValue(L.DESC_MACRO_SETVAR, "Sets a local variable.");
        setValue(L.DESC_MACRO_ADDVAR, "Adds a number to a local variable (or appends text).");
        setValue(L.DESC_MACRO_INCVAR, "Increments a local variable and returns the new value.");
        setValue(L.DESC_MACRO_DECVAR, "Decrements a local variable and returns the new value.");
        setValue(L.DESC_MACRO_HASVAR, "\"true\" if the local variable exists.");
        setValue(L.DESC_MACRO_DELETEVAR, "Deletes a local variable.");
        setValue(L.DESC_MACRO_GETGLOBALVAR, "Value of a global variable. Global variables are shared by the whole manuscript.");
        setValue(L.DESC_MACRO_SETGLOBALVAR, "Sets a global variable.");
        setValue(L.DESC_MACRO_ADDGLOBALVAR, "Adds a number to a global variable (or appends text).");
        setValue(L.DESC_MACRO_INCGLOBALVAR, "Increments a global variable and returns the new value.");
        setValue(L.DESC_MACRO_DECGLOBALVAR, "Decrements a global variable and returns the new value.");
        setValue(L.DESC_MACRO_HASGLOBALVAR, "\"true\" if the global variable exists.");
        setValue(L.DESC_MACRO_DELETEGLOBALVAR, "Deletes a global variable.");
        setValue(L.DESC_MACRO_RANDOM, "Random choice, different every time.");
        setValue(L.DESC_MACRO_PICK, "Random choice that stays the same for the manuscript.");
        setValue(L.DESC_MACRO_ROLL, "Dice roll (e.g. 2d6+3).");
        setValue(L.DESC_MACRO_MAX_PROMPT, "Maximum prompt size (context minus response tokens).");
        setValue(L.DESC_MACRO_MAX_CONTEXT_TOKENS, "Maximum context size in tokens.");
        setValue(L.DESC_MACRO_MAX_RESPONSE_TOKENS, "Maximum response size in tokens.");
        setValue(L.DESC_MACRO_MODEL, "Name of the used model.");
        setValue(L.DESC_MACRO_LAST_GENERATION_TYPE, "Type of the generation (normal, regenerate, swipe, quiet).");
        setValue(L.DESC_MACRO_NEWLINE, "Inserts newline(s).");
        setValue(L.DESC_MACRO_SPACE, "Inserts space(s).");
        setValue(L.DESC_MACRO_NOOP, "Does nothing, renders as empty text.");
        setValue(L.DESC_MACRO_TRIM, "Removes newlines around itself.");
        setValue(L.DESC_MACRO_REVERSE, "Reverses the text.");
        setValue(L.DESC_MACRO_IF, "Renders content only if the condition (macro, variable or text) is truthy. Supports ! negation.");
        setValue(L.DESC_MACRO_VARIABLE_SHORTHAND, "Variable shorthands: . for local, $ for global. Operators: = ++ -- += -= || ?? ||= ??= == != > >= < <=");
        setValue(L.DESC_MACRO_COMMENT, "Comment, removed from the output.");
        setValue(L.DESC_TEMPLATE_SUMMARY_BLOCKS, "The summaries being merged, oldest first.");

    }

    @Override
    public Locale getLocale() {
        return Locale.US;
    }

    @Override
    public DateFormat getDateFormat() {
        return new SimpleDateFormat("MM/dd/yyyy");
    }

    @Override
    public DateFormat getHourFormat() {
        return new SimpleDateFormat("HH:mm:ss");
    }

    @Override
    public DateFormat getDateHourFormat() {
        return new SimpleDateFormat("MM/dd/yyyy HH:mm:ss");
    }
}
