package com.github.enerccio.marginalia.domain.service.impl.generation;

public enum Events {

    BEFORE_PREPARE_GENERATION,
    AFTER_PREPARE_GENERATION,
    BEFORE_PREPARE_CONSTANT_DATA,
    AFTER_STATIC_TEMPLATE_DATA,
    AFTER_PREPARE_CONSTANT_DATA,
    BEFORE_PROCESS_LOREBOOK,
    PROCESS_LOREBOOKS,
    PROCESS_LOREBOOK_ENTRY,
    PROCESS_ACTIVATED_ENTRIES,
    AFTER_PROCESS_LOREBOOK,
    BEFORE_PREPARE_CONTENT,
    AFTER_MANUSCRIPT_CONCATENATION,
    AFTER_PREPARE_CONTENT,
    BEFORE_GENERATE_NEW_MESSAGE,
    AFTER_GENERATE_NEW_MESSAGE,
    BEFORE_PREPARE_PAYLOAD,
    AFTER_PREPARE_PAYLOAD,
    BEFORE_INFERENCE,
    REASONING_CHUNK_RECEIVED,
    CHUNK_RECEIVED,
    AFTER_INFERENCE,
    BEFORE_CLEANUP,
    AFTER_CLEANUP

}
