# Set root logger level to INFO and its appender to stdout
log4j.rootLogger=INFO, stdout

# Direct log messages to stdout
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.Target=System.out
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout

# Define the output format: Date [Thread] Level Category - Message
log4j.appender.stdout.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} [%t] %-5p %c{1} - %m%n

# Set a more detailed log level (DEBUG) for your specific project package
log4j.logger.com.github.enerccio=DEBUG
log4j.logger.org.apache.catalina=DEBUG
logger.com.vaadin=DEBUG
log4j.logger.org.springframework.web=DEBUG